### ISSUE TITLE
element.addEventListener is not a function

### ISSUE THREAD

**Issue by cyberbobjr** [vlio20/angular-datepicker#142]
Hi,
You have a bug for the catching event of keypress in date-picker.component.js, you must replace this line (259) :

````
    DatePickerComponent.prototype.startGlobalListeners = function () {
        var _this = this;
        this.globalListnersUnlisteners.push(this.renderer.listen('document', 'keydown', function (e) {
            _this.onKeyPress(e);
        }));
    };
````
with this (remove the quotes around document)

````
    DatePickerComponent.prototype.startGlobalListeners = function () {
        var _this = this;
        this.globalListnersUnlisteners.push(this.renderer.listen(document, 'keydown', function (e) {
            _this.onKeyPress(e);
        }));
    };
````

Tested and worked with Angular 2.4 (yep :/))

**Comment by vlio20** [comment]
Want to PR?
