### ISSUE TITLE
error TypeError: o.inputBlurred is not a function

### ISSUE THREAD

**Issue by melodysummer** [vlio20/angular-datepicker#429]
2.10.2 version
![image](https://user-images.githubusercontent.com/25784493/45343132-92799000-b5d2-11e8-9b87-fee4ec99acf3.png)

in the builded js file, inpuBlurred is not packed in.
fixed up as follows:
esm5/ng2-date-picker.js
DatePickerDirective.prototype.onBlur = function () {
        this.datePicker.inputBlurred();
    };

**Comment by vlio20** [comment]
@melodysummer can you please provide steps to reproduce?

**Comment by melodysummer** [comment]
@vlio20 after I upgraded the version to 2.10.2,  when I click the calendar date, the console will show error as above, said  inputBlurred is not a function.

**Comment by vlio20** [comment]
I will check it ASAP, PRs would be much appreciated

**Comment by vlio20** [comment]
@melodysummer I am unable to reproduce :(. On which component are we talking about?

**Comment by vlio20** [comment]
closing for now
