### ISSUE TITLE
2.6.1 - is month mode broken?

### ISSUE THREAD

**Issue by dgroh** [vlio20/angular-datepicker#291]
When setting the `month` mode, I get the following error:

> current.clone is not a function

This occurs in:

```
    Object.defineProperty(MonthCalendarComponent.prototype, "currentDateView", {
        get: function () {
            return this._currentDateView;
        },
        set: function (current) {
            this._currentDateView = current.clone();
            this.yearMonths = this.monthCalendarService
                .generateYear(this.componentConfig, this._currentDateView, this.selected);
            this.navLabel = this.monthCalendarService.getHeaderLabel(this.componentConfig, this.currentDateView);
            this.showLeftNav = this.monthCalendarService.shouldShowLeft(this.componentConfig.min, this._currentDateView);
            this.showRightNav = this.monthCalendarService.shouldShowRight(this.componentConfig.max, this.currentDateView);
            this.showSecondaryLeftNav = this.componentConfig.showMultipleYearsNavigation && this.showLeftNav;
            this.showSecondaryRightNav = this.componentConfig.showMultipleYearsNavigation && this.showRightNav;
        },
        enumerable: true,
        configurable: true
    });
```

I created a stackblitz demonstrating the issue: https://stackblitz.com/edit/ng2-date-picker-bug

It works fine in `day` mode

It also works in the version `2.6.0`

**Comment by vlio20** [comment]
Will take a look asap.

**Comment by vlio20** [comment]
@dgroh, the stackblitz you provided is broken. pls provide a working one.

**Comment by dgroh** [comment]
I deleted it by mistake. I'll provide a new one by tomorrow. Much appreciated

**Comment by dgroh** [comment]
I got it https://stackblitz.com/edit/ng2-date-picker

Select a a date for 2020 for example in the Date From

Try to select any month in the in the Date To

You can also not navigate back and forward...

I mentioned before this was not an issue in 2.6.0

**Comment by vlio20** [comment]
when update the config (without accessing it via ViewChild) it seems to be working:
https://stackblitz.com/edit/ng2-date-picker-9xq5gj

**Comment by vlio20** [comment]
@dgroh, please close if verified.

**Comment by dgroh** [comment]
ok, the `displayDate` was also a problem I guess

thanks @vlio20
